import PDFDocument from "pdfkit";
import Prediction from "../models/Prediction.js";

export async function downloadReport(req, res) {
  try {
    const prediction = await Prediction.findOne({
      _id: req.params.id,
      userId: req.userId,
    });
    if (!prediction) {
      return res.status(404).json({ error: "Prediction not found" });
    }

    const doc = new PDFDocument({ margin: 50 });
    const filename = `AutoPriceAI_${prediction.make}_${prediction.model}.pdf`.replace(/\s+/g, "_");

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    doc.pipe(res);

    doc
      .fontSize(22)
      .fillColor("#12151B")
      .text("AutoPrice AI - Valuation Report", { align: "left" })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .fillColor("#666666")
      .text(`Generated on ${new Date().toLocaleString()}`)
      .moveDown(1.5);

    doc
      .fontSize(14)
      .fillColor("#12151B")
      .text(`${prediction.make} ${prediction.model}`, { underline: true })
      .moveDown(0.5);

    doc.fontSize(11).fillColor("#333333");
    const rows = [
      ["Type", prediction.type],
      ["Origin", prediction.origin],
      ["Drive Train", prediction.driveTrain],
      ["Engine Size (L)", prediction.engineSize],
      ["Cylinders", prediction.cylinders],
      ["Horsepower", prediction.horsepower],
      ["City MPG", prediction.mpgCity],
      ["Highway MPG", prediction.mpgHighway],
      ["Weight (lbs)", prediction.weight],
      ["Wheelbase (in)", prediction.wheelbase],
      ["Length (in)", prediction.length],
    ];
    rows.forEach(([label, value]) => {
      doc.text(`${label}:  ${value}`);
    });

    doc.moveDown(1);
    doc
      .fontSize(20)
      .fillColor("#F2A93B")
      .text(`Predicted Price: $${Number(prediction.predictedPrice).toLocaleString()}`)
      .moveDown(1);

    if (prediction.explanation?.length) {
      doc.fontSize(13).fillColor("#12151B").text("Why this price:").moveDown(0.3);
      doc.fontSize(11).fillColor("#333333");
      prediction.explanation.forEach((line) => doc.text(`•  ${line}`));
    }

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor("#999999")
      .text(
        "This is an estimate generated by a machine learning model trained on historical listing data. Actual market value may vary.",
        { align: "left" }
      );

    doc.end();
  } catch (err) {
    res.status(500).json({ error: "Could not generate report", details: err.message });
  }
}
